<a href="https://colab.research.google.com/github/AdityaTiwary533-max/Just_a_demo/blob/main/Basic_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
def check(marks):
  if marks>=26:
    print("Pass")
  else:
    print("Fail")
check(85)
check(21)

Pass
Fail


In [4]:
import numpy as np

In [9]:
marks = np.array([78, 91, 55, 72, 40, 88])
print(marks[marks<60])
print(marks[(marks>=60)&(marks<=90)])

[55 40]
[78 72 88]


In [10]:
from google.colab import files
uploaded=files.upload()

Saving session4_dummy_students_data.csv to session4_dummy_students_data.csv


In [11]:
import pandas as pd
df=pd.read_csv("session4_dummy_students_data.csv")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [12]:
print(df.head())

   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69   
1         102   Diya   16    Delhi    91       88       94   
2         103  Kabir   17  Mathura    55       61       58   
3         104  Meera   16    Noida    72       79       81   
4         105  Rohan   17   Mumbai    40       52       47   

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9   
1                  96                    11                     10   
2                  75                     5                      6   
3                  89                     7                      8   
4                  68                     3                      5   

   final_project_score  
0                   82  
1                   93  
2                   60  
3                   78  
4                   45  


In [15]:
print(df.columns)

Index(['student_id', 'name', 'age', 'city', 'math', 'science', 'english',
       'attendance_percent', 'study_hours_per_week', 'assignments_submitted',
       'final_project_score'],
      dtype='object')


In [16]:
print(df.shape)

(20, 11)


In [17]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   student_id             20 non-null     int64 
 1   name                   20 non-null     object
 2   age                    20 non-null     int64 
 3   city                   20 non-null     object
 4   math                   20 non-null     int64 
 5   science                20 non-null     int64 
 6   english                20 non-null     int64 
 7   attendance_percent     20 non-null     int64 
 8   study_hours_per_week   20 non-null     int64 
 9   assignments_submitted  20 non-null     int64 
 10  final_project_score    20 non-null     int64 
dtypes: int64(9), object(2)
memory usage: 1.8+ KB
None


In [19]:
math_scores = df["math"].to_numpy()
print(math_scores)
print(type(math_scores))
print(math_scores.mean())

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]
<class 'numpy.ndarray'>
69.5


In [22]:
english_scores = df["english"].to_numpy()
print(english_scores)
print(type(english_scores))
print(english_scores.mean())

[69 94 58 81 47 90 66 89 51 85 72 79 42 91 60 96 65 83 46 80]
<class 'numpy.ndarray'>
72.2


In [21]:
df["average"] = df[["math","science","english"]].mean(axis=1)
print(df[["name","math","science","english","average"]])

      name  math  science  english    average
0    Aarav    78       84       69  77.000000
1     Diya    91       88       94  91.000000
2    Kabir    55       61       58  58.000000
3    Meera    72       79       81  77.333333
4    Rohan    40       52       47  46.333333
5     Sara    88       93       90  90.333333
6   Ishaan    64       70       66  66.666667
7   Ananya    95       92       89  92.000000
8   Vivaan    48       57       51  52.000000
9     Tara    83       76       85  81.333333
10   Arjun    67       63       72  67.333333
11   Nisha    74       81       79  78.000000
12     Dev    35       45       42  40.666667
13   Priya    89       86       91  88.666667
14   Kunal    58       54       60  57.333333
15    Riya    92       90       96  92.666667
16      Om    61       69       65  65.000000
17   Aditi    80       85       83  82.666667
18    Yash    43       49       46  46.000000
19   Sneha    77       73       80  76.666667


In [24]:
top_students=df[df["average"]>=85]
print(top_students[["name","average"]])

      name    average
1     Diya  91.000000
5     Sara  90.333333
7   Ananya  92.000000
13   Priya  88.666667
15    Riya  92.666667


In [25]:
low_attendance = df[df["attendance_percent"]<75]
print(low_attendance[["name","attendance_percent"]])

      name  attendance_percent
4    Rohan                  68
8   Vivaan                  71
12     Dev                  62
18    Yash                  66


In [26]:
location=df[df["city"]=="Mathura"]
print(location[["name","city"]])

      name     city
2    Kabir  Mathura
6   Ishaan  Mathura
10   Arjun  Mathura
14   Kunal  Mathura
18    Yash  Mathura


In [28]:
students=df[df["assignments_submitted"]<6]
print(students[["name","assignments_submitted"]])

     name  assignments_submitted
4   Rohan                      5
12    Dev                      4
18   Yash                      5


In [33]:
import pandas as pd
df=pd.read_csv("session4_dummy_students_data.csv")
#1
df["average"] = df[["math", "science", "english"]].mean(axis=1)
print(df[["math", "science", "english", "average"]])
#2
def get_result(avg):
  if avg >=55:
    return "Pass"
  return "fail"
#3
print("Class average:", df["average"].mean())
print("Max average:", df["average"].max())
print("Min average:", df["average"].min())
#4
print("Class Average:", df["average"].mean())
#5
top_students=df[df['average']>=85]
print(top_students[["name","average"]])
#6
low_attendance=df[df["attendance_percent"]<75]
print(low_attendance[["name","attendance_percent"]])
#7

    math  science  english    average
0     78       84       69  77.000000
1     91       88       94  91.000000
2     55       61       58  58.000000
3     72       79       81  77.333333
4     40       52       47  46.333333
5     88       93       90  90.333333
6     64       70       66  66.666667
7     95       92       89  92.000000
8     48       57       51  52.000000
9     83       76       85  81.333333
10    67       63       72  67.333333
11    74       81       79  78.000000
12    35       45       42  40.666667
13    89       86       91  88.666667
14    58       54       60  57.333333
15    92       90       96  92.666667
16    61       69       65  65.000000
17    80       85       83  82.666667
18    43       49       46  46.000000
19    77       73       80  76.666667
Class average: 71.35000000000001
Max average: 92.66666666666667
Min average: 40.666666666666664
Class Average: 71.35000000000001
      name    average
1     Diya  91.000000
5     Sara  90.333333
7   Ana